### ISSUE TITLE
Error encountered during docker-compose pull

### ISSUE THREAD

**Issue by etcy** [ONLYOFFICE/docker-onlyoffice-nextcloud#42]
I was trying to update my NC by running docker-compose pull.

I could not get pass the following no matter how many times I tried. Any ideas?
(I was sucessful when going from 19.01 -> 19.02 a week ago. Today I was hoping to go from 19.02 to 19.03)

```
Pulling app                        ... download complete
Pulling onlyoffice-document-server ... extracting (100.0%)
Pulling nginx                      ... done

ERROR: for app  failed to register layer: Error processing tar file(exit status 2): panic: regexp: Compile(`(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\.(?:[a-zA-Z0-9]|[a-]*)[a-z0-9]+)+)?-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?`): error parsing regexp: unexpected ): `(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\.(?:[a-zA-Z0-9]|[a-]*)[a-z0-9]+)+)?-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?`

goroutine 1 [running]:
regexp.MustCompile(0xc000200000, 0xe7, 0xb0)
        /usr/local/go/src/regexp/regexp.go:311 +0x154
github.com/docker/docker/vendor/github.com/docker/distribution/reference.expression(0xc000156840, 0x3, 0x3, 0xc000155e00)
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/reference/regexp.go:115 +0x95
github.com/docker/docker/vendor/github.com/docker/distribution/reference.init()
        /root/rpmbuild/BUILD/src/engine/.gopath/src/github.com/docker/docker/vendor/github.com/docker/distribution/reference/regexp.go:53 +0x8c0


ERROR: for onlyoffice-document-server  failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
ERROR: failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
```

**Comment by etcy** [comment]
I have not managed to solve this yet but I think this is docker related and not due to onlyoffice-nextcloud.
As such I will close this issue. Sorry for the mistake.
